<?php require __dir__."/../layout/app.phtml"?>
<script>
function add (id) {
    document.getElementById('id').value=id;
    document.getElementById('add').submit();
}
</script>
jméno: <?=$uname?><br />
třída: <?=$class?><br />

<form class="form-horizontal" method="post" action="<?=$router->pathFor('search')?>">
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <div class="form-group">
        <label class="col-md-4 control-label" for="bookName">Vyhledejte knihu:</label>
        <div class="col-md-6">
            <input class="form-control" type="text" name="bookName" id="bookName" required autofocus>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
            <input class="btn btn-primary" type="submit" value="Hledat">
        </div>
    </div>
</form>

Díla:<br />
<?php
    if (is_array(@$books)) {
        echo "<table>";
        echo "<tr><td>Autor</td><td>Dílo</td><td>Období</td><td>Žánr</td><td></td></tr>";
        foreach($books as $book) {
            echo "<tr><td>$book[0]</td><td>$book[1]</td><td>$book[2]</td><td>$book[3]</td><td><button onclick='add($book[4])'>Odebrat</button></td></tr>" . PHP_EOL;
        }
        ?>
</table>
<form method="post" class="form" action="<?=$router->pathFor('books')?>" id="add">
    <input type="hidden" name="_METHOD" value="DELETE" />
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="hidden" name="id" id="id" >
</form>
<?php
    } else {
        echo "Nemáte přidané žádné knihy."; 
    }
?>
